apiVersion: v1 
kind: Service
metadata:
  labels:
    app: restairline 
    tier: backend
  name: sql-data
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: restairline 
    tier: backend
  type: LoadBalancer
---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sql-data
  labels:
    app: restairline
spec:
  selector:
    matchLabels:
      app: restairline
      tier: backend
  template:
    metadata:
      labels:
        app: restairline
        tier: backend
    spec:
      containers:
        - name: sql-data
          image: microsoft/mssql-server-linux:2017-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: RestAirline123
