apiVersion: v1
kind: Secret
metadata:
  name: mssql 
type: Opaque
stringData:
  SA_PASSWORD: RestAirline123
  EventStoreConnectionString: Server=mssql;Database=RestAirline;User Id=sa;Password=RestAirline123
  ReadModelConnectionString: Server=mssql;Database=RestAirlineRead;User Id=sa;Password=RestAirline123
